apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: testnamespace
bases:
- ../../../base/enterprise-gateway
patchesStrategicMerge:
- patches/enterprise-gateway/deployment.yaml
- patches/enterprise-gateway/ingress.yaml
resources: 
- namespace.yaml