apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-logging
bases: 
- ../../../base/fluentbit
- ../../../base/kibana
resources: 
- resources/namespace.yaml
- resources/volumes
patchesJson6902:
  - path: patches/kibpatchingress.json
    target:
      group: extensions
      kind: Ingress
      name: kibana-ingress
      version: v1beta1
