apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-master-elasticsearch-master-2
  namespace: kube-logging
spec:
  accessModes:
  - ReadWriteMany
  dataSource: null
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeName: es-2-pv
